- packages/gatsby-theme-blog-core/README.md
- packages/gatsby-theme-blog-core/gatsby-node.js
- packages/gatsby-theme-blog-core/src/templates/post-query.js
- packages/gatsby-theme-blog/README.md
- packages/gatsby-theme-blog/package.json
- packages/gatsby-theme-blog/src/components/post.js
- packages/gatsby-theme-blog/src/components/seo.js
- starters/theme/package.json
- yarn.lock
Keywords are no longer used by most major search engines.
> Remove keywords from SEO

- packages/gatsby-theme-blog-core/src/components/post-date.js
- packages/gatsby-theme-blog-core/src/components/post-hero.js
- packages/gatsby-theme-blog-core/src/components/post-link.js
- packages/gatsby-theme-blog-core/src/components/post-list.js
- packages/gatsby-theme-blog-core/src/components/post-title.js
- packages/gatsby-theme-blog-core/src/components/post.js
- packages/gatsby-theme-blog-core/src/components/posts.js
Add only the components so they can be leveraged. No Layout, footer, header extras.
> Add JSX components to blog-core

- packages/gatsby-theme-blog-core/src/components/post-link.js
- packages/gatsby-theme-blog-core/src/components/post.js
- packages/gatsby-theme-blog/src/components/post-link.js
- packages/gatsby-theme-blog/src/components/post.js
Already merged in the main gatsby repo. So going to merge this in.
> use more semantic html

- packages/gatsby-theme-blog-core/README.md
- packages/gatsby-theme-blog-core/gatsby-config.js
- packages/gatsby-theme-blog-core/gatsby-node.js
- packages/gatsby-theme-blog-core/src/components/post-hero.js
- packages/gatsby-theme-blog-core/src/templates/post-query.js
- packages/gatsby-theme-blog-core/utils/default-options.js
Make maxWidth a configurable option and apply it to the featured image as well as markdown images run through remark.
> Make maxWidth for images configurable

- packages/gatsby-theme-blog/gatsby-browser.js
- packages/gatsby-theme-blog/package.json
- packages/gatsby-theme-blog/src/components/header.js
- packages/gatsby-theme-blog/src/components/layout.js
- yarn.lock
> Add skip nav

- packages/gatsby-theme-blog/src/components/seo.js
Borrowing a pattern I saw Dustin use which treats SEO conditionally depending on whether an image exists or not. Prevents the awkward empty space of summary-large-card on twitter.
> Conditional seo

- packages/gatsby-theme-blog/README.md
- packages/gatsby-theme-blog/gatsby-config.js
- packages/gatsby-theme-blog/gatsby-node.js
- packages/gatsby-theme-blog/src/hooks/configOptions.js
- packages/gatsby-theme-notes/README.md
Thought through this a lot, but I don't think we need both this and ignorePreset since this is unlikely to be used going forward without a combination of the switch toggle and a built-in preset.
Also included an updated README since explaining this behavior to Max was sufficiently confusing!
> Remove disable flag

- packages/gatsby-theme-blog-core/src/components/post-hero.js
- packages/gatsby-theme-blog-darkmode/src/gatsby-theme-blog/components/header.js
- packages/gatsby-theme-blog/src/components/bio-content.js
- packages/gatsby-theme-blog/src/components/header.js
- packages/gatsby-theme-blog/src/components/layout.js
- packages/gatsby-theme-blog/src/components/post-footer.js
- packages/gatsby-theme-blog/src/components/post-hero.js
- packages/gatsby-theme-blog/src/gatsby-theme-blog-core/components/post.js
- packages/gatsby-theme-blog/src/gatsby-theme-blog-core/components/posts.js
Following changes to Gatsby docs and other packages
> Remove uses of un-named components to adhere to best practices

- packages/gatsby-theme-blog-core/README.md
- packages/gatsby-theme-blog-core/src/components/post-date.js
- packages/gatsby-theme-blog-core/src/components/post-hero.js
- packages/gatsby-theme-blog-core/src/components/post-link.js
- packages/gatsby-theme-blog-core/src/components/post-title.js
- packages/gatsby-theme-blog-core/src/components/post.js
I'm not wedded to any of these names or choices. Open to input since this is potentially an opinionated set of additions.
> Add class names to the core theme

- packages/gatsby-theme-blog-darkmode/src/gatsby-plugin-theme-ui/index.js
- packages/gatsby-theme-blog/package.json
- packages/gatsby-theme-notes/package.json
- packages/gatsby-theme-ui-preset/src/index.js
- yarn.lock
Remove unnecessary dependencies and update theme-ui keyword
> remove unecessary dependencies

- packages/gatsby-theme-blog-darkmode/README.md
- packages/gatsby-theme-blog/README.md
Adding additional information to the README to note breaking changes.
> Migration guide

- README.md
Updating README for official cutover
> Repo readme

- packages/gatsby-theme-blog-darkmode/package.json
> Update package.json for darkmode theme

- .github/workflows/cypress.yml
- yarn.lock
The dirty lock file kept breaking tests after renovatebot ran. This attempts to solve that.
> Rerun yarn to update lock file automatically

- packages/gatsby-theme-blog/src/components/posts.js
Thank you for developing the great tools !
I thought that it would be better if the default title for SEO was {siteTile} rather than "Home".
> change seo title from "Home" to {siteTitle}

- packages/gatsby-theme-blog-core/package.json
- packages/gatsby-theme-notes/package.json
- packages/gatsby-theme-ui-preset/package.json
> chore: Update package homepages

- README.md
Updates the list of themes to be consistent with all the themes in the packages directory.
> Update list of themes in README

- packages/gatsby-theme-i18n/src/components/seo.js
- packages/gatsby-theme-i18n/src/hooks/use-localization.js
The lack of query names was breaking our build
> add names to queries

- starters/theme/README.md
Gatsby logo were missing from Docs as website have changed to new domain. Fixed images and links
> Fix(README): Fixed broken image link and links

- packages/gatsby-theme-blog-core/gatsby-node.js
- packages/gatsby-theme-blog-core/src/templates/post-query.js
- packages/gatsby-theme-blog/src/components/post-hero-caption.js
- packages/gatsby-theme-blog/src/components/post-hero.js
- starters/theme/content/posts/hello-world.mdx
- starters/theme/content/posts/my-second-post/index.mdx
Feature for #87
Adds imageCaptionText and imageCaptionLink blogPost front matter properties which are used to conditionally include a hero caption with or without an external link.
> feat(post-hero-caption): Add ability to have hero captions

- packages/gatsby-theme-i18n/src/components/seo.js
The lang value should be "en-US", not the code
> fix(gatsby-theme-i18n): Correct HTML lang
